### PR TITLE
docs: Rebrand to Revenge

### PR DESCRIPTION
**Pull request by Cristiandis**

### CODE REVIEW

**Review by Rico040 — CHANGES_REQUESTED** [review]
Use discord link from organization readme.

**Comment by Cristiandis** [comment]
> Use discord link from organization readme.

done

**Review by Rico040 — APPROVED** [review]

**Comment by oSumAtrIX** [comment]
Hey, rebranding is difficult. We will rebrand everything in one go and that includes everything to its best, not just the readme. Doing a clean job is difficult which is why we will look into it ourselves. In the future i recommend opening an issue before working on a PR before wasting time in it if it's closed. This will be mentioned in the upcoming contribution guidelines too, thanks

**Comment by ALMIGHTY-VC** [comment]
Hoping that the rebrand goes smoothly

**Comment by Cristiandis** [comment]
> Hey, rebranding is difficult. We will rebrand everything in one go and that includes everything to its best, not just the readme. Doing a clean job is difficult which is why we will look into it ourselves. In the future i recommend opening an issue before working on a PR before wasting time in it if it's closed. This will be mentioned in the upcoming contribution guidelines too, thanks

i did this mostly for consistency because looks weird that the tweak is all branded and the rest of the repo is still half bunny and half revenge, its up to you to merge it when it's needed

**Comment by oSumAtrIX** [comment]
We're gonna work repository by repository, ideally one clean PR each that does a full one rebrand at once, if that makes sense

**Pull request closed without merging**
